### ISSUE TITLE
Método Registrar da error

### ISSUE THREAD

**Issue by jmcarreiro** [scolozzo81/RemisesNicolasWeb#4]
Request:

POST http://remises.jmce.webfactional.com/api/registrar HTTP/1.1
Host: remises.jmce.webfactional.com
Connection: keep-alive
Content-Length: 131
User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/67.0.3396.99 Safari/537.36
Cache-Control: no-cache
Origin: chrome-extension://fhbjgbiflinjbdggehcddcbncdddomop
Postman-Token: 9a47a7b7-0012-2193-c29e-37657eb09b36
Content-Type: application/json
Accept: */*
Accept-Encoding: gzip, deflate
Accept-Language: es-AR,es;q=0.9,en-US;q=0.8,en;q=0.7
Cookie: XSRF-TOKEN=eyJpdiI6InIxN0trMXRuMlUzZFZEWkxRTzZsa1E9PSIsInZhbHVlIjoicm5od0JSbE1QZVVWdENWRFdSc3k1UXg4Qkw2dUtlYXZYZ1wvaldBaFlGVkFPMEsxVVo2REZkeEFFeTN1dFlaWmhnb1cxWjloQXhRZ0txT1k2ajdBTWx3PT0iLCJtYWMiOiI4NmVmOWYwMWQxYWZmOTUxZTZiMWVhMTRjNTI5M2EzZmQ3ZThmYjY4NDFjZmQ5ZDM4MmNhMDNhZTQxYmJjMzA3In0%3D; laravel_session=eyJpdiI6ImFRcytiQzFFRWRnbTY4U0JqYms1OXc9PSIsInZhbHVlIjoiYnVZUHVHeWtMUFBcL2lqak40VVBpMSt1QzR4RnZEXC9BN2pKdCtnanh5R3JZOENXNUt6YWRxV3dST0dEbjJ2Q3NTM1g4TmRYTTlRbGJzcVNzaXhWS0FUZz09IiwibWFjIjoiMzc4M2YyZjIwMDcwYTI3NjU3MDE5ZjY3MTgyMzY1MWExNTRlNWZkODM4YmIxMGQzODVjYWZiMTA4MDdmZDc2MyJ9

{
	email:'juan.prueba@gmail.com',
	password:'secret',
	cliente : {
		nombre:'Juan',
		apellido:'Prueba',
		telefono:'40570155'
	}
}

Response:

HTTP/1.1 200 OK
Server: nginx
Date: Fri, 20 Jul 2018 12:09:56 GMT
Content-Type: application/json
Connection: keep-alive
Vary: Accept-Encoding
Cache-Control: private, must-revalidate
pragma: no-cache
expires: -1
X-RateLimit-Limit: 60
X-RateLimit-Remaining: 59
Content-Length: 382

{"id":{"headers":{},"original":"No se pudo crear: SQLSTATE[23000]: Integrity constraint violation: 1048 Column 'name' cannot be null (SQL: insert into `users` (`name`, `email`, `password`, `updated_at`, `created_at`) values (, , $2y$10$dWn4DE8DF895C9x0GxW0Ye8jg7lU9uG2kItwQnt6JHXBSZjD7Rbjq, 2018-07-20 12:09:56, 2018-07-20 12:09:56))","exception":null},"status":"FAIL","error":null}

**Comment by DanielGuerrero94** [comment]
podes probar poniendole comillas a las key y a los values
{
"email":"juan.prueba@gmail.com",
"password":"secret",
"cliente":{
"nombre":"Juan",
"apellido":"Prueba",
"telefono":"40570155"
}
}
