### ISSUE TITLE
Método Actualizar Perfil no modifica datos

### ISSUE THREAD

**Issue by jmcarreiro** [scolozzo81/RemisesNicolasWeb#6]
Request:

PUT http://remises.jmce.webfactional.com/api/usuarios/33 HTTP/1.1
Host: remises.jmce.webfactional.com
Connection: keep-alive
Content-Length: 33
User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/67.0.3396.99 Safari/537.36
Cache-Control: no-cache
Origin: chrome-extension://fhbjgbiflinjbdggehcddcbncdddomop
Postman-Token: ad9d4f61-b290-5dc9-435f-f3a9182b4788
Content-Type: application/json
Accept: */*
Accept-Encoding: gzip, deflate
Accept-Language: es-AR,es;q=0.9,en-US;q=0.8,en;q=0.7
Cookie: XSRF-TOKEN=eyJpdiI6InIxN0trMXRuMlUzZFZEWkxRTzZsa1E9PSIsInZhbHVlIjoicm5od0JSbE1QZVVWdENWRFdSc3k1UXg4Qkw2dUtlYXZYZ1wvaldBaFlGVkFPMEsxVVo2REZkeEFFeTN1dFlaWmhnb1cxWjloQXhRZ0txT1k2ajdBTWx3PT0iLCJtYWMiOiI4NmVmOWYwMWQxYWZmOTUxZTZiMWVhMTRjNTI5M2EzZmQ3ZThmYjY4NDFjZmQ5ZDM4MmNhMDNhZTQxYmJjMzA3In0%3D; laravel_session=eyJpdiI6ImFRcytiQzFFRWRnbTY4U0JqYms1OXc9PSIsInZhbHVlIjoiYnVZUHVHeWtMUFBcL2lqak40VVBpMSt1QzR4RnZEXC9BN2pKdCtnanh5R3JZOENXNUt6YWRxV3dST0dEbjJ2Q3NTM1g4TmRYTTlRbGJzcVNzaXhWS0FUZz09IiwibWFjIjoiMzc4M2YyZjIwMDcwYTI3NjU3MDE5ZjY3MTgyMzY1MWExNTRlNWZkODM4YmIxMGQzODVjYWZiMTA4MDdmZDc2MyJ9

{
	cliente:{
		nombre:'Juan'
	}
}

Responde 200 OK sin ningún cuerpo.
El cliente asociado al usuario id=33 no modifica sus datos.

**Comment by DanielGuerrero94** [comment]
Cuidado con no agregar , despues de testing porque termina siendo un json mal formateado.

{
"cliente":{
"nombre":"Juan",
"apellido":"Testing"
}
}
